---
name: Question
description: Ask a question about the project
labels: question
body:
    - type: textarea
      id: question
      attributes:
          label: Question
          description: What do you want to ask?
          placeholder: Your question
      validations:
          required: true
    - type: textarea
      id: context
      attributes:
          label: Context
          description: Provide context for your question
    - type: textarea
      id: info
      attributes:
          label: Additional Info
          description: Any other relevant information
